### ISSUE TITLE
Extension Tracker URL error (Separate from server url defined in settings)

### ISSUE THREAD

**Issue by Enhancifire** [Suwayomi/tachiyomi-extension#12]
### Steps to reproduce

Suwayomi Extension is set to ip address 100.x.x.x in Mihon. Trackers are set up to sync Suwayomi server with Mihon.
User clicks on tracking tab in manga details page.

### Expected behavior

Popup should contain the correct number of chapters and update accordingly.

### Actual behavior

Tracker is showing "Suwayomi error: Failed to connect to /192.168.1.6:4567".
Updating the manga through the server works. It's only the tracker that's not working.

![WhatsApp Image 2024-10-30 at 22 58 20_b1ba7abb](https://github.com/user-attachments/assets/8843b6c3-cf13-46bc-aef1-9b048766a003)
![WhatsApp Image 2024-10-30 at 22 58 20_41c1a5d5](https://github.com/user-attachments/assets/5ee55f7e-6ef0-451a-b77a-6fed236def37)

### App version

1.4.16

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [X] I will fill out all of the requested information in this form.

**Comment by cpiber** [comment]
1) That IP in the error is not the IP you configured. Either you didn't restart Mihon after changing the IP, or there is an error on the source for this manga
2) Latest Mihon had a major refactor of the tracker, everything that works with the extension should now always work with the tracker, so this issue should not happen anymore
